### PR TITLE
 readme changed

### LINKED ISSUE #10: Take screenshots of the available pages and add it to the Project README
Take a screenshot of the home page and  create page and add them to the project README

### PR DESCRIPTION
**Pull request by Sinjini46**
added screenshot of the home page and create page to the project README
Fixes #10

### CODE REVIEW

**Review by Judge-Paul — COMMENTED** [review]
Hey @Sinjini46 , can you add a heading for each page screenshot

**Comment by Sinjini46** [comment]
sure

**Comment by Sinjini46** [comment]
i have made the necessary changes

**Review by Judge-Paul — APPROVED** [review]

**Comment by Judge-Paul** [comment]
> i have made the necessary changes

@Sinjini46 thanks for your contribution

**Pull request merged**
