### PR TITLE
feat: persist formData in localStorage

### LINKED ISSUE #16: feat: persist form data
Currently the form data is stored in state so if a user accidentally refreshes their page or the page reloads the data they've entered will be lost. To solve this you can persist the data using local storage.

### PR DESCRIPTION
**Pull request by sid-js**
## Description

This PR address the issue #16 and adds the feature to persist form data.

## Changes Made

- Add functionality to store the formData in localStorage.
- Retrieve the stored formData(if any) on page load and populate the form.

## Checklist

- [x] I have read the [CONTRIBUTING.md](./CONTRIBUTING.md) document.
- [x] My code follows the coding guidelines of the project.
- [x] I have tested my changes thoroughly.
- [x] I have added/updated relevant documentation.
- [x] I have updated any necessary unit tests.
- [x] My commits follow the commit guidelines.

Fixes #16

### CODE REVIEW

**Review by Judge-Paul — COMMENTED** [review]
Hey @sid-js can you clear the data in localstorage after the form is submitted, I'd have done this but this is still your PR

**Comment by sid-js** [comment]
> Hey @sid-js can you clear the data in localstorage after the form is submitted, I'd have done this but this is still your PR

Sure, would do this.

**Comment by sid-js** [comment]
I've added functionality to clear the localStorage once the cover letter is generated successfully (if there are errors, the users still have the option to edit the previous formData that is not cleared)

**Comment by Judge-Paul** [comment]
@sid-js Thanks alot for your contribution

**Pull request merged**
